_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0]]
  PROPOSAL_GENERATOR:
    NAME: "ClsFreeRPN"
  RPN:
    HEAD_NAME: "ClsFreeRPNHead"
    BBOX_REG_LOSS_TYPE: "iou"
    BBOX_REG_LOSS_WEIGHT: 0.5
    POST_NMS_TOPK_TRAIN: 2000
    IOU_THRESHOLDS_OBJECTNESS: [0.1, 0.3]
    POSITIVE_FRACTION_OBJECTNESS: 1.0
    CTR_REG_LOSS_WEIGHT: 0.5
    NMS_THRESH: 1.0
    NMS_THRESH_TEST: 1.0
  ROI_HEADS:
    NAME: "OpensetROIHeads"
    OBJ_SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 1.0
    KNOWN_SCORE_THRESH: 0.05
    KNOWN_NMS_THRESH: 0.5
    KNOWN_TOPK: 50
    UNKNOWN_SCORE_THRESH: 0.0
    UNKNOWN_NMS_THRESH: 0.5
    UNKNOWN_TOPK: 50
    NUM_CLASSES: 81
    NUM_KNOWN_CLASSES: 20
    UNKNOWN_ID: 1000
  ROI_BOX_HEAD:
    CLS_LOSS_WEIGHT: 0.9
    BBOX_REG_LOSS_WEIGHT: 0.5
    IOU_REG_LOSS_WEIGHT: 0.5
  PLN:
    EMD_DIM: 256
    ALPHA: 0.1
    BETA: 0.9
    DISTANCE_TYPE: "COS"
    REPS_PER_CLASS: 1
    IOU_THRESHOLD: 0.5
    UNK_THR: 0.23
    LOSS_WEIGHT: 0.5
DATASETS:
  TRAIN: ('voc_2007_train', 'voc_2012_trainval')
  TEST: ('voc_2007_test', 'voc_coco_20_40_test', 'voc_coco_20_60_test', 'voc_coco_20_80_test', 'voc_coco_2500_test', 'voc_coco_5000_test', 'voc_coco_10000_test', 'voc_coco_20000_test')
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (84000, 116000)
  MAX_ITER: 128000
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 10000
TEST:
  DETECTIONS_PER_IMAGE: 1000
