_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0]]
  PROPOSAL_GENERATOR:
    NAME: "ClsFreeRPN"
  RPN:
    HEAD_NAME: "ClsFreeRPNHead"
    BBOX_REG_LOSS_TYPE: "iou"
    BBOX_REG_LOSS_WEIGHT: 10.0
    POST_NMS_TOPK_TRAIN: 2000
    IOU_THRESHOLDS_OBJECTNESS: [0.1, 0.3]
    POSITIVE_FRACTION_OBJECTNESS: 1.0
    CTR_REG_LOSS_WEIGHT: 1.0
    NMS_THRESH: 1.0
    NMS_THRESH_TEST: 1.0
  ROI_HEADS:
    NAME: "OpensetROIHeads"
    OBJ_SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 1.0
    KNOWN_SCORE_THRESH: 0.05
    KNOWN_NMS_THRESH: 0.5
    KNOWN_TOPK: 50
    UNKNOWN_SCORE_THRESH: 0.0
    UNKNOWN_NMS_THRESH: 0.5
    UNKNOWN_TOPK: 50
    NUM_CLASSES: 88
    NUM_KNOWN_CLASSES: 28
    UNKNOWN_ID: 1000
  ROI_BOX_HEAD:
    CLS_LOSS_WEIGHT: 1.5
    BBOX_REG_LOSS_WEIGHT: 2.0
    IOU_REG_LOSS_WEIGHT: 1.0
  PLN:
    EMD_DIM: 256
    ALPHA: 0.05
    BETA: 0.95
    DISTANCE_TYPE: "COS"
    REPS_PER_CLASS: 1
    IOU_THRESHOLD: 0.5
    UNK_THR: 0.09
    LOSS_WEIGHT: 2.0
DATASETS:
  TRAIN: ("graspnet_train",)
  TEST: ("graspnet_test_1", "graspnet_test_2", "graspnet_test_3", "graspnet_test_4", "graspnet_test_5", "graspnet_test_6")
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (84000, 116000)
  MAX_ITER: 128000
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 10000
TEST:
  DETECTIONS_PER_IMAGE: 1000
